# tasks for Red Hat Familly
---
- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_selinux.status == 'enabled'

- name: repository rpm installation
  yum:
      name: {{ xtradb_repo_rpm }}
      state: present


...
